Merge Feature/0.3 (#18)
* Replace background color action with color action
Move background color action to miscellaneous section
Set action icons in the respective class constructors rather than in the settings action

* Replace background color action with color action
Move background color action to miscellaneous section
Set action icons in the respective class constructors rather than in the settings action

* Make use of resettable color action API

* Remove old context menu

* Adhere to updated actions API

* Removed nest level in data context menu

* Adhere to updated actions API

* Auto select subsets after creation

* Small cosmetic changes

* Refactor actions

* Use widget action label widget

* Use widget action label widget

* Work on drag and drop

* Pass factory to plugin

* Cluster color data is working again

* Small refactor

* Prevent cluster set drop when already loaded

* Add cluster action
Better integration with data hierarchy item
Refactor here and there

* Fix small bug

* Fix bug

* Fix bug

* Remove redundant dialog
Update cluster action

* Basic manual clustering is working

* Small refactor

* Small ui changes

* Small ui changes

* Small ui changes

* hasSelection

* Small ui change

* Refactor

* Incorporate cluster API changes

* Work with new dataset ref API

* Small refactor

* Incorporate data hierarchy item changes

* Update color dataset name when renamed

* Fix compile error c2371

* Small refactor

* Fix styling issues

* No uses the color map action

* Fix small bug

* Custom color map ranges

* Enable/disable range editing in color map

* Small change

* Implement plugin factory method that returns the plugin icon

* Remove temporary HSNE selection code from scatterplot

* Add selection icons

* Update actions

* Remove superfluous mouse tracking call

* Feature/0.3 images meta data (#17)

* Moved pixel selection tool and renderer to core
Small changes to actions

* Use pixel selection tool from the core

* Add icon retrieval to pixel selection tool

* Remove redundant includes

* Work on pixel selection integration

* Use pixel selection action from the core

* Adhere to new actions API

* End of day commit

* Small changes

* Action API change

Co-authored-by: Thomas Kroes <t.kroes@lumc.nl>

* Enable feature/0.3 build

Co-authored-by: Thomas Kroes <t.kroes@lumc.nl>
Co-authored-by: ThomasKroes <tkroes81@gmail.com>
Co-authored-by: B. van Lew <b.van_lew@lumc.nl>